version: '2'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:7.0'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=testDB
      - MONGODB_ROOT_PASSWORD=rootpassword
